{ FetchError: request to https://raw.githubusercontent.com/kotori-y/admetMesh-bot/master/data/sample.smi failed, reason: connect ETIMEDOUT 185.199.110.133:443
    at ClientRequest.<anonymous> (/home/runner/work/admetMesh-Bot/admetMesh-Bot/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://raw.githubusercontent.com/kotori-y/admetMesh-bot/master/data/sample.smi failed, reason: connect ETIMEDOUT 185.199.110.133:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
